version: '3'

services:
  consumer_services:
    image: jamesoy/ducs_consumer_services:latest
    ports:
      - 8070:8080
    links:
      - admin_server
    volumes:
      - /tmp:/tmp
      - /app/logs/ducs:/app/logs/ducs
    environment:
      - ADMIN_SERVER_URL=http://admin_server:8090

  admin_server:
    image: jamesoy/ducs_admin_server:latest
    ports:
      - 8090:8090
    volumes:
      - "/tmp:/tmp"

